#!/bin/bash

set -v #echo on
./proj1-checker job.sms solution.txt
./proj1-checker tests/t1.sms tests/t1.txt
./proj1-checker tests/t1_d.sms tests/t1_d.txt
./proj1-checker tests/t2.sms tests/t2.txt
./proj1-checker tests/t2_d.sms tests/t2_d.txt
./proj1-checker tests/t3.sms tests/t3.txt
./proj1-checker tests/t3_d.sms tests/t3_d.txt
./proj1-checker tests/t4_d.sms tests/t4_d.txt
./proj1-checker tests/t4.sms tests/t4.txt
./proj1-checker tests/t5.sms tests/t5.txt